DROP TABLE  `TEST_DS_0`.`SHARDING_TABLE_ROUTE`;
CREATE TABLE `TEST_DS_0`.`SHARDING_TABLE_ROUTE` (
  `ROUTE_ID` INT NOT NULL AUTO_INCREMENT,
  `DATABASE_TYPE` VARCHAR(255) NULL,
  `DATABASE_NAME` VARCHAR(255) NULL,
  `URL` VARCHAR(255) NULL,
  `USER_NAME` VARCHAR(255) NULL,
  `PASSWORD` VARCHAR(255) NULL,
  PRIMARY KEY (`ROUTE_ID`));


DROP TABLE `TEST_DS_0`.`BANK_A_USER_HISTORICAL_OPERATION_0`;
CREATE TABLE `TEST_DS_0`.`BANK_A_USER_HISTORICAL_OPERATION_0` (
  `OPERATION_ID` BIGINT(50) NOT NULL,
  `OPERATION_TYPE_ID` INT NOT NULL,
  `USER_ID` BIGINT(50) NOT NULL,
  `CORRELATIVE_OPERATION_ID` BIGINT(50),
  `AMOUNT` DOUBLE,
  `REASON` VARCHAR(1024) NULL,
  `STATUS` VARCHAR(255) NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`OPERATION_ID`),
  UNIQUE INDEX `OPERATION_ID_UNIQUE` (`OPERATION_ID` ASC));

  
DROP TABLE `TEST_DS_1`.`BANK_A_USER_HISTORICAL_OPERATION_1`;
CREATE TABLE `TEST_DS_1`.`BANK_A_USER_HISTORICAL_OPERATION_1` (
  `OPERATION_ID` BIGINT(50) NOT NULL,
  `OPERATION_TYPE_ID` INT NOT NULL,
  `USER_ID` BIGINT(50) NOT NULL,
  `CORRELATIVE_OPERATION_ID` BIGINT(50),
  `AMOUNT` DOUBLE,
  `REASON` VARCHAR(1024) NULL,
  `STATUS` VARCHAR(255) NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`OPERATION_ID`),
  UNIQUE INDEX `OPERATION_ID_UNIQUE` (`OPERATION_ID` ASC));
  
  
  
DROP TABLE `TEST_DS_0`.`BANK_B_USER_HISTORICAL_OPERATION_0`;
CREATE TABLE `TEST_DS_0`.`BANK_B_USER_HISTORICAL_OPERATION_0` (
  `OPERATION_ID` BIGINT(50) NOT NULL,
  `OPERATION_TYPE_ID` INT NOT NULL,
  `USER_ID` BIGINT(50) NOT NULL,
  `CORRELATIVE_OPERATION_ID` BIGINT(50),
  `AMOUNT` DOUBLE,
  `REASON` VARCHAR(1024) NULL,
  `STATUS` VARCHAR(255) NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`OPERATION_ID`),
  UNIQUE INDEX `OPERATION_ID_UNIQUE` (`OPERATION_ID` ASC));
  
CREATE INDEX BBUHO_0_COID_IDX ON BANK_B_USER_HISTORICAL_OPERATION_0(CORRELATIVE_OPERATION_ID);
  
DROP TABLE `TEST_DS_1`.`BANK_B_USER_HISTORICAL_OPERATION_1`;
CREATE TABLE `TEST_DS_1`.`BANK_B_USER_HISTORICAL_OPERATION_1` (
  `OPERATION_ID` BIGINT(50) NOT NULL,
  `OPERATION_TYPE_ID` INT NOT NULL,
  `USER_ID` BIGINT(50) NOT NULL,
  `CORRELATIVE_OPERATION_ID` BIGINT(50),
  `AMOUNT` DOUBLE,
  `REASON` VARCHAR(1024) NULL,
  `STATUS` VARCHAR(255) NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`OPERATION_ID`),
  UNIQUE INDEX `OPERATION_ID_UNIQUE` (`OPERATION_ID` ASC));
  
  CREATE INDEX BBUHO_1_COID_IDX ON BANK_B_USER_HISTORICAL_OPERATION_1(CORRELATIVE_OPERATION_ID);


DROP TABLE `TEST_DS_0`.`BANK_A_ACCOUNT_0`;
CREATE TABLE `TEST_DS_0`.`BANK_A_ACCOUNT_0` (
  `USER_ID` BIGINT(50) NOT NULL,
  `USER_NAME` VARCHAR(255) NULL,
  `GEOGRAPHY_ID` INT(20) NOT NULL,
  `ACCOUNT_TYPE` VARCHAR(255) NULL,
  `BALANCE` DOUBLE NOT NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC));
  
  DROP TABLE `TEST_DS_1`.`BANK_A_ACCOUNT_1`;
CREATE TABLE `TEST_DS_1`.`BANK_A_ACCOUNT_1` (
  `USER_ID` BIGINT(50) NOT NULL,
  `USER_NAME` VARCHAR(255) NULL,
  `GEOGRAPHY_ID` INT(20) NOT NULL,
  `ACCOUNT_TYPE` VARCHAR(255) NULL,
  `BALANCE` DOUBLE NOT NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC));
  
  
  DROP TABLE `TEST_DS_0`.`BANK_B_ACCOUNT_0`;
CREATE TABLE `TEST_DS_0`.`BANK_B_ACCOUNT_0` (
  `USER_ID` BIGINT(50) NOT NULL,
  `USER_NAME` VARCHAR(255) NULL,
  `GEOGRAPHY_ID` INT(20) NOT NULL,
  `ACCOUNT_TYPE` VARCHAR(255) NULL,
  `BALANCE` DOUBLE NOT NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC));
  
  DROP TABLE `TEST_DS_1`.`BANK_B_ACCOUNT_1`;
  CREATE TABLE `TEST_DS_1`.`BANK_B_ACCOUNT_1` (
  `USER_ID` BIGINT(50) NOT NULL,
  `USER_NAME` VARCHAR(255) NULL,
  `GEOGRAPHY_ID` INT(20) NOT NULL,
  `ACCOUNT_TYPE` VARCHAR(255) NULL,
  `BALANCE` DOUBLE NOT NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC));
  
  
  
  CREATE TABLE `TEST_DS_0`.`BANK_A_TIME_TABLE` (
  `TIME_TABLE_ID` BIGINT(50) NOT NULL AUTO_INCREMENT,
  `NEW_UPDATED_TIME` DATETIME(6) NOT NULL,
  `CREATED_BY` VARCHAR(255) NULL,
  `CREATED_DATE` DATETIME(6) NULL,
  `MODIFIED_BY` VARCHAR(255) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`TIME_TABLE_ID`));
  
  CREATE TABLE `TEST_DS_0`.`BANK_B_TIME_TABLE` (
  `TIME_TABLE_ID` BIGINT(50) NOT NULL AUTO_INCREMENT,
  `NEW_UPDATED_TIME` DATETIME(6) NOT NULL,
  `CREATED_BY` VARCHAR(255) NULL,
  `CREATED_DATE` DATETIME(6) NULL,
  `MODIFIED_BY` VARCHAR(255) NULL,
  `MODIFIED_DATE` DATETIME(6) NULL,
  PRIMARY KEY (`TIME_TABLE_ID`));
